Tested cache simulator.
Added the larger arrays to the cache simulation.
Added /bigobj to debug compiler option to fix Fatal Error C1128  . I really dont know what i changed to cause this????